---
abstract: 'cron based timers for AnyEvent'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Timer-Cron
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  DateTime: 0
  DateTime::Event::Cron: 0
  Moo: 1.000007
  Safe::Isa: 0
  Task::Weaken: 0
  namespace::clean: 0
  perl: 5.8
resources:
  homepage: http://github.com/haarg/AnyEvent-Timer-Cron
  repository: git://github.com/haarg/AnyEvent-Timer-Cron.git
version: 0.001000
